local M = {}

-- local Menu = require("nui.menu")
--
-- local menu = Menu({
--   position = "50%",
--   size = {
--     width = 40,
--     height = 5,
--   },
--   border = {
--     style = "single",
--     padding = { 0, 2 },
--     text = {
--       top = "[Choose-an-Element]",
--       top_align = "center",
--     },
--   },
--   win_options = {
--     winhighlight = "Normal:Normal,FloatBorder:Normal",
--   },
-- }, {
--   lines = {
--     Menu.item("Hydrogen (H)"),
--     Menu.item("Carbon (C)"),
--     Menu.item("Nitrogen (N)"),
--     Menu.separator("Noble-Gases", {
--       char = "-",
--       text_align = "center",
--     }),
--     Menu.item("Helium (He)"),
--     Menu.item("Neon (Ne)"),
--     Menu.item("Argon (Ar)"),
--   },
--   max_width = 20,
--   keymap = {
--     focus_next = { "j", "<Down>", "<Tab>" },
--     focus_prev = { "k", "<Up>", "<S-Tab>" },
--     close = { "<Esc>", "<C-c>" },
--     submit = { "<CR>", "<Space>" },
--   },
--   on_close = function()
--     print("Menu Closed!")
--   end,
--   on_submit = function(item)
--     print("Menu Submitted: ", item.text)
--   end,
-- })
--
-- -- mount the component
-- menu:mount()

return M
